version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:develop
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy HPStrategyTF

  #freqtrade_bt:
  #  image: freqtradeorg/freqtrade:develop
  #  restart: unless-stopped
  #  container_name: freqtrade_bt
  #  volumes:
  #    - "./user_data:/freqtrade/user_data"
  #    - "/etc/localtime:/etc/localtime:ro"
  #  ports:
  #    - "8081:8080"
  #  command: >
  #    webserver
  #    --logfile /freqtrade/user_data/logs/freqtrade_bt.log
  #    --config /freqtrade/user_data/config.json

  proxy:
    image: mikekonan/exchange-proxy:latest-amd64
    deploy:
      replicas: 1
    restart: unless-stopped
    ports:
      - "8888:8080"
    container_name: proxy
    command: -verbose 1
